#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
artifact_dir="${root_dir}/deliverables/artifacts"

mkdir -p "${artifact_dir}"

{
  echo "# Verification Log"
  echo
  echo "Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "## local_smoke"
  echo
  "${root_dir}/scripts/local_smoke.sh"
  echo
  echo "status: passed"
} > "${artifact_dir}/verification_log.md"

"${root_dir}/scripts/benchmark_local.sh" > "${artifact_dir}/policy_benchmark.csv"
"${root_dir}/scripts/dump_plan.sh" all_reduce 1048576 8 > "${artifact_dir}/all_reduce_plan.csv"
"${root_dir}/scripts/dump_plan.sh" all_gather 1048576 8 > "${artifact_dir}/all_gather_plan.csv"
"${root_dir}/scripts/dump_plan.sh" reduce_scatter 1048576 8 > "${artifact_dir}/reduce_scatter_plan.csv"

cat > "${artifact_dir}/README.md" <<'EOF'
# Artifacts

This directory contains locally reproducible outputs for the current scaffold.

- `verification_log.md`: smoke test execution summary.
- `policy_benchmark.csv`: simulator benchmark output.
- `all_reduce_plan.csv`: generated AllReduce communication plan.
- `all_gather_plan.csv`: generated AllGather communication plan.
- `reduce_scatter_plan.csv`: generated ReduceScatter communication plan.

These files are generated by:

```bash
./scripts/collect_artifacts.sh
```
EOF

echo "artifacts written to ${artifact_dir}"
